language: go

os: linux

go:
  - "1.10.x"
  - "1.11.x"
  - master

before_install:
  - sudo apt-get install tcpdump

install:
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - go get -t -d ./...

script:
  - go vet ./...
  - golint -set_exit_status ./...
  - go test -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
